defmodule Mix.Tasks.Compile.Unused do
  use Mix.Task.Compiler

  @shortdoc "Find unused public functions"

  @moduledoc """
  Compile project and find uncalled public functions.

  ### Warning

  This isn't perfect solution and this will not find dynamic calls in form of:

      apply(mod, func, args)

  So this mean that, for example, if you have custom `child_spec/1` definition
  then this will return such function as unused even when you are using that
  indirectly in your supervisor.

  ## Configuration

  You can define used functions by adding `mfa` in `unused: [ignored: [⋯]]`
  in your project configuration:

      def project do
        [
          # ⋯
          unused: [
            ignore: [
              {MyApp.Foo, :child_spec, 1}
            ]
          ],
          # ⋯
        ]
      end

  ## Options

  - `severity` - severity of the reported messages, defaults to `hint`.
    Other allowed levels are `information`, `warning`, and `error`.
  """

  @recursive true

  # These are functions generated by Elixir and Erlang, this list probably
  # should not grow.
  @built_ins [
    __info__: 1,
    __struct__: 0,
    __struct__: 1,
    __impl__: 1,
    module_info: 0,
    module_info: 1,
    behaviour_info: 1
  ]

  @options [
    severity: :string
  ]

  alias MixUnused.Tracer

  @impl true
  def run(argv) do
    {opts, _rest, []} = OptionParser.parse(argv, strict: @options)
    {:ok, _pid} = Tracer.start_link()

    tracers = Code.get_compiler_option(:tracers)
    Mix.Task.Compiler.after_compiler(:app, &after_compiler(&1, tracers, opts))
    Code.put_compiler_option(:tracers, [Tracer | tracers])

    {:ok, []}
  end

  defp after_compiler({status, diagnostics}, tracers, opts) do
    # Cleanup tracers after compilation
    Code.put_compiler_option(:tracers, tracers)

    severity = Keyword.get(opts, :severity, "hint") |> severity()
    unused = all_functions(Mix.Project.config()[:app]) -- Tracer.get_calls()
    :ok  = Tracer.stop()

    messages =
      for {m, f, a} <- filter_ignored(unused) do
        %Mix.Task.Compiler.Diagnostic{
          compiler_name: "unused",
          message: "#{inspect(m)}.#{f}/#{a} is unused",
          severity: severity,
          position: nil,
          file: "unknown"
        }
        |> print_diagnostic()
      end

    {status, messages ++ diagnostics}
  end

  defp all_functions(app) do
    _ = Application.unload(app)
    :ok = Application.load(app)

    # Check exported functions without loading modules as this could cause
    # unexpected behaviours in case of `on_load` callbacks
    app
    |> Application.spec(:modules)
    |> Enum.flat_map(fn mod ->
      with path when is_list(path) <- :code.which(mod),
           beam = File.read!(path),
           {:ok, {^mod, [{:exports, exports}, {:attributes, attr}]}} <-
             :beam_lib.chunks(beam, [:exports, :attributes]) do
        callbacks =
          attr
          |> Keyword.get(:behaviour, [])
          |> callbacks()

        for {name, arity} <- exports,
            {name, arity} not in @built_ins,
            {name, arity} not in callbacks,
            do: {mod, name, arity}
      else
        _ -> []
      end
    end)
  end

  defp callbacks(behaviours) do
    # We need to load behaviours as there is no other way to get list of
    # callbacks than to call `behaviour_info/1`
    Enum.flat_map(behaviours, & &1.behaviour_info(:callbacks))
  end

  defp filter_ignored(functions) do
    Mix.Project.config()
    |> Keyword.get(:unused, [])
    |> Keyword.get(:ignore, [])
    |> Enum.map(fn
      {_m, _f, _a} = entry -> entry
      {m, f} -> {m, f, :_}
      m when is_atom(m) -> {m, :_, :_}
    end)
    |> Enum.map(&{&1, [], [:"$_"]})
    |> case do
      [] ->
        functions

      spec ->
        match_spec = :ets.match_spec_compile(spec)
        ignored = :ets.match_spec_run(functions, match_spec)

        functions -- ignored
    end
  end

  defp severity("hint"), do: :hint
  defp severity("info"), do: :information
  defp severity("information"), do: :information
  defp severity("warn"), do: :warning
  defp severity("warning"), do: :warning
  defp severity("error"), do: :error

  defp print_diagnostic(diag) do
    Mix.shell().info([level(diag.severity), diag.message])

    diag
  end

  defp level(level), do: [:bright, color(level), "#{level}: ", :reset]

  defp color(:error), do: :red
  defp color(:warning), do: :yellow
  defp color(_), do: :blue
end
